# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hZnHi0lpFan2HRYkFhKSjgbDRf7Lal3e
"""



# Commented out IPython magic to ensure Python compatibility.
 %%writefile app.py
 import streamlit as st
 import pandas as pd
 import seaborn as sns
 import matplotlib.pyplot as plt
 
 Set page config
 st.set_page_config(page_title="EDA - Temperature Data", layout="wide")
 
 Title
 st.title("📊 Exploratory Data Analysis - Temperature Data of China (Beijing)")
 
  Load data
 uploaded_file = "Programming__For_DataAnalysis_Assessment (8).ipynb"
 try:
     df = pd.read_csv(uploaded_file)
     st.success("Data loaded successfully!")
 except Exception as e:
     st.error(f"Error loading data: {e}")
     st.stop()





